In [69]:
import pandas as pd
import pandas.tseries.offsets as offsets

In [2]:
data = pd.read_csv("../data/track_A.csv")

In [3]:
data

                date    キロ程   高低左   高低右   通り左   通り右    水準    軌間     速度
0         2017-04-01  10000 -1.16 -0.23  1.20  1.20  0.83  3.89  84.00
1         2017-04-01  10001 -1.17 -0.30  1.88  1.88  0.67  4.63  84.00
2         2017-04-01  10002 -1.09 -0.19  2.30  2.30  0.50  5.33  84.00
3         2017-04-01  10003 -0.64  0.20  2.28  2.28  0.46  5.90  84.00
4         2017-04-01  10004  0.47  0.89  1.74  1.74  0.62  6.38  84.50
5         2017-04-01  10005  2.10  1.63  0.82  0.82  0.93  6.87  84.50
6         2017-04-01  10006  3.61  1.89 -0.18 -0.18  1.30  7.38  84.50
7         2017-04-01  10007  4.05  1.12 -0.91 -0.91  1.60  7.78  85.00
8         2017-04-01  10008  2.71 -0.83 -1.20 -1.20  1.66  7.80  85.00
9         2017-04-01  10009 -0.29 -3.42 -1.13 -1.13  1.21  7.25  85.00
10        2017-04-01  10010 -3.92 -5.60 -1.02 -1.02  0.12  6.11  85.00
11        2017-04-01  10011 -6.65 -6.30 -1.17 -1.17 -1.49  4.65  85.00
12        2017-04-01  10012 -7.25 -5.05 -1.65 -1.65 -3.13  3.18  85.00
13        2017-04-01  10013 -5.39 -2.25 -2.21 -2.21 -4.21  1.87  85.00
14        2017-04-01  10014 -1.87  1.09 -2.44 -2.44 -4.45  0.76  85.00
15        2017-04-01  10015  1.83  3.81 -2.03 -2.03 -4.05 -0.14  85.00
16        2017-04-01  10016  4.21  5.13 -1.02 -1.02 -3.57 -0.76  85.00
17        2017-04-01  10017  4.40  4.81  0.22  0.22 -3.47 -1.01  85.00
18        2017-04-01  10018  2.55  3.16  1.19  1.19 -3.79 -0.98  85.00
19        2017-04-01  10019 -0.37  0.86  1.48  1.48 -4.19 -0.95  85.00
20        2017-04-01  10020 -3.03 -1.32  0.99  0.99 -4.25 -1.15  85.00
21        2017-04-01  10021 -4.37 -2.75 -0.04 -0.04 -3.80 -1.59  85.00
22        2017-04-01  10022 -4.08 -3.16 -1.20 -1.20 -2.98 -2.03  85.00
23        2017-04-01  10023 -2.66 -2.75 -2.10 -2.10 -2.11 -2.22  85.50
24        2017-04-01  10024 -1.04 -2.01 -2.47 -2.47 -1.44 -2.16  85.50
25        2017-04-01  10025  0.02 -1.38 -2.28 -2.28 -1.02 -2.04  85.50
26        2017-04-01  10026  0.37 -0.93 -1.67 -1.67 -0.78 -2.13  86.00
27        2017-04-01  10027  0.39 -0.39 -0.84 -0.84 -0.66 -2.50  86.00
28        2017-04-01  10028  0.58  0.54 -0.01 -0.01 -0.62 -3.03  86.00
29        2017-04-01  10029  1.06  1.78  0.66  0.66 -0.63 -3.52  86.00
...              ...    ...   ...   ...   ...   ...   ...   ...    ...
10185660  2018-03-31  37876 -3.93 -2.65  2.15  2.39 -1.17 -0.98  39.00
10185661  2018-03-31  37877 -1.71 -1.32  1.77  1.55 -0.66 -1.25  39.00
10185662  2018-03-31  37878  0.98  0.29  1.64  0.69  0.32 -1.06  39.00
10185663  2018-03-31  37879  3.08  1.49  1.69  0.47  1.36 -0.62  39.00
10185664  2018-03-31  37880  3.75  1.79  1.72  1.16  1.92 -0.53  39.00
10185665  2018-03-31  37881  2.84  1.04  1.64  2.55  1.78 -1.22  39.00
10185666  2018-03-31  37882  0.87 -0.49  1.61  4.04  1.26 -2.46  39.00
10185667  2018-03-31  37883 -1.21 -2.17  1.94  5.06  0.88 -3.39  39.00
10185668  2018-03-31  37884 -2.50 -3.22  2.82  5.33  0.89 -3.25  39.00
10185669  2018-03-31  37885 -2.56 -3.10  4.10  5.02  1.05 -2.05  39.00
10185670  2018-03-31  37886 -1.56 -1.78  5.34  4.67  0.92 -0.60  38.19
10185671  2018-03-31  37887 -0.10  0.16  6.12  4.78  0.34  0.14  38.00
10185672  2018-03-31  37888  1.10  1.86  6.36  5.57 -0.40 -0.13  38.00
10185673  2018-03-31  37889  1.60  2.60  6.34  6.81 -0.86 -0.89  38.00
10185674  2018-03-31  37890  1.32  2.19  6.45  8.01 -0.82 -1.26  38.00
10185675  2018-03-31  37891  0.59  1.03  6.91  8.69 -0.52 -0.79  38.00
10185676  2018-03-31  37892 -0.17 -0.22  7.60  8.65 -0.34  0.24  38.00
10185677  2018-03-31  37893 -0.59 -1.00  8.17  8.04 -0.45  1.23  38.00
10185678  2018-03-31  37894 -0.62 -1.13  8.33  7.19 -0.71  1.76  38.00
10185679  2018-03-31  37895 -0.43 -0.81  8.05  6.50 -0.89  1.91  38.00
10185680  2018-03-31  37896 -0.27 -0.41  7.54  6.21 -0.94  2.00  38.00
10185681  2018-03-31  37897 -0.27 -0.11  7.06  6.34 -1.03  2.18  38.00
10185682  2018-03-31  37898 -0.28  0.15  6.72  6.72 -1.33  2.31  38.00
10185683  2018-03-31  37899 -0.02  0.60  6.51  7.06 -1.73  2.19  38.00
10185684  2018-03-31  37900  0.67  1.40  6.33  7.10 -1.98  1.89  38.00
10185685  2018-03-31  37901  1.65  2.40  6.09  6.69 -1.91  1.74  38.00
10185686  2018-03-31  37902  2.45  3.18  5.75  5.86 -1.63  2.04  37.19
10185687  2018-03-31  37903  2.59  3.23  5.21  4.79 -1.43  2.67  37.00
10185688  2018-03-31  37904  1.90  2.33  4.35  3.67 -1.40  3.17  37.00
10185689  2018-03-31  37905  0.68  0.77  3.08  2.63 -1.39  3.14  37.00

[10185690 rows x 9 columns]

In [4]:
kilo10000 = data.loc[data["キロ程"] == 10000,]
kilo10000

                date    キロ程   高低左   高低右   通り左   通り右    水準    軌間    速度
0         2017-04-01  10000 -1.16 -0.23  1.20  1.20  0.83  3.89  84.0
27906     2017-04-02  10000 -0.81 -0.16  2.40  2.40  1.11  4.14  84.0
55812     2017-04-03  10000 -0.99 -0.22  2.37  2.37  0.50  3.91  84.0
83718     2017-04-04  10000   NaN   NaN   NaN   NaN   NaN   NaN  54.0
111624    2017-04-05  10000 -0.97 -0.33  2.51  2.73  0.50  3.28  45.0
139530    2017-04-06  10000 -1.48 -0.94  1.68  1.68  1.41  4.26  62.0
167436    2017-04-07  10000 -0.66 -0.26  3.46  3.54  1.29  2.99  43.0
195342    2017-04-08  10000 -1.29 -0.73  0.96  0.96  0.86  3.76  84.0
223248    2017-04-09  10000 -0.98 -0.29  2.68  2.68  0.94  3.46  52.0
251154    2017-04-10  10000 -1.63 -0.65  1.36  1.36  0.60  3.85  85.0
279060    2017-04-11  10000 -1.10 -0.44  3.10  3.10  0.99  3.58  59.0
306966    2017-04-12  10000 -0.54 -0.20  0.95  1.63  0.91  1.67  29.0
334872    2017-04-13  10000 -1.31 -0.51  0.84  0.84  0.52  3.82  83.0
362778    2017-04-14  10000 -1.29 -0.33  1.02  1.02  0.77  3.86  84.0
390684    2017-04-15  10000   NaN   NaN   NaN   NaN   NaN   NaN   NaN
418590    2017-04-16  10000 -1.45 -0.50  0.66  0.66  0.64  3.49  84.0
446496    2017-04-17  10000 -0.94 -0.11  3.33  3.33  0.76  3.05  52.0
474402    2017-04-18  10000 -1.18 -0.26  1.25  1.25  0.85  3.63  84.0
502308    2017-04-19  10000   NaN   NaN   NaN   NaN   NaN   NaN  84.0
530214    2017-04-20  10000 -1.11 -0.40  3.33  3.33  1.14  3.39  54.5
558120    2017-04-21  10000 -1.18 -0.67  3.34  3.30  1.04  2.93  49.0
586026    2017-04-22  10000 -1.38 -0.45  1.33  1.33  0.59  3.78  84.0
613932    2017-04-23  10000 -1.31 -0.34  1.14  1.14  1.18  4.32  84.0
641838    2017-04-24  10000 -1.24 -0.32  1.22  1.22  0.55  3.99  80.0
669744    2017-04-25  10000 -0.76 -0.10  3.16  3.16  0.77  2.97  52.0
697650    2017-04-26  10000 -1.11 -0.48  2.56  2.59  0.77  1.21  49.0
725556    2017-04-27  10000 -1.62 -0.73  1.44  1.44  0.83  4.17  83.0
753462    2017-04-28  10000 -1.43 -0.46  1.14  1.14  0.90  4.11  84.7
781368    2017-04-29  10000 -1.18 -0.55  1.78  1.78  1.03  4.13  80.5
809274    2017-04-30  10000 -1.34 -0.42  1.80  1.80  0.65  4.07  84.0
...              ...    ...   ...   ...   ...   ...   ...   ...   ...
9348510   2018-03-02  10000   NaN   NaN   NaN   NaN   NaN   NaN   NaN
9376416   2018-03-03  10000 -0.37  1.10  2.41  0.81 -0.82  4.77  51.0
9404322   2018-03-04  10000  0.95  1.26  1.40  0.64 -4.45  5.95  80.0
9432228   2018-03-05  10000  0.18  1.42  1.80  0.96 -0.19  3.77  61.0
9460134   2018-03-06  10000 -7.99 -3.84  1.65  3.55 -4.33 -0.35  54.0
9488040   2018-03-07  10000  1.60  3.14  2.37  1.69 -0.26  4.11  85.0
9515946   2018-03-08  10000  1.07  2.17  2.26  1.00  0.31  4.31  75.0
9543852   2018-03-09  10000 -7.63 -3.85  2.35  4.20 -4.21 -0.39  46.0
9571758   2018-03-10  10000   NaN   NaN   NaN   NaN   NaN   NaN   NaN
9599664   2018-03-11  10000 -6.95 -2.99  1.86  4.08 -4.66  0.79  52.0
9627570   2018-03-12  10000 -7.56 -3.27  0.60  2.72 -4.77  0.56  55.0
9655476   2018-03-13  10000  0.19  1.30  2.78  1.33 -0.25  4.18  50.0
9683382   2018-03-14  10000  0.40  1.35  1.04 -0.06  0.16  4.30  84.0
9711288   2018-03-15  10000 -6.96 -2.71  1.74  4.23 -4.80  0.73  56.0
9739194   2018-03-16  10000  0.00  0.98  2.98  1.70 -0.02  4.37  56.0
9767100   2018-03-17  10000 -7.73 -3.61  0.62  2.72 -4.48  0.98  51.0
9795006   2018-03-18  10000  1.08  2.35  2.81  2.09 -0.44  4.30  84.0
9822912   2018-03-19  10000  0.57  1.80  2.55  1.65 -0.32  4.21  56.0
9850818   2018-03-20  10000   NaN   NaN   NaN   NaN   NaN   NaN   NaN
9878724   2018-03-21  10000   NaN   NaN   NaN   NaN   NaN   NaN   NaN
9906630   2018-03-22  10000   NaN   NaN   NaN   NaN   NaN   NaN   NaN
9934536   2018-03-23  10000   NaN   NaN   NaN   NaN   NaN   NaN   NaN
9962442   2018-03-24  10000   NaN   NaN   NaN   NaN   NaN   NaN   NaN
9990348   2018-03-25  10000   NaN   NaN   NaN   NaN   NaN   NaN   NaN
10018254  2018-03-26  10000   NaN   NaN   NaN   NaN   NaN   NaN   NaN
10046160  2018-03-27  10000   NaN   NaN   NaN   NaN   NaN   NaN   NaN
10074066  2018-03-28  10000   NaN   NaN   NaN   NaN   NaN   NaN   NaN
10101972  2018-03-29  10000   NaN   NaN   NaN   NaN   NaN   NaN   NaN
10129878  2018-03-30  10000 -0.50  0.74  3.52  2.28 -0.18  4.36  53.0
10157784  2018-03-31  10000 -6.98 -2.79  1.41  3.87 -4.72  0.80  51.0

[365 rows x 9 columns]

In [5]:
kilo10001 = data.loc[data["キロ程"] == 10001,]
kilo10002 = data.loc[data["キロ程"] == 10002,]
kilo10003 = data.loc[data["キロ程"] == 10003,]
kilo10004 = data.loc[data["キロ程"] == 10004,]

kilo10013 = data.loc[data["キロ程"] == 10013,]
kilo10014 = data.loc[data["キロ程"] == 10014,]
kilo10015 = data.loc[data["キロ程"] == 10015,]
kilo10016 = data.loc[data["キロ程"] == 10016,]
kilo10017 = data.loc[data["キロ程"] == 10017,]

In [8]:
kilo10000_interpolate =  kilo10000.interpolate(method='index')
kilo10000_interpolate

,date,キロ程,高低左,高低右,通り左,通り右,水準,軌間,速度
0,2017-04-01,10000,-1.160000,-0.230000,1.200000,1.200000,0.830000,3.890000,84.000000
27906,2017-04-02,10000,-0.810000,-0.160000,2.400000,2.400000,1.110000,4.140000,84.000000
55812,2017-04-03,10000,-0.990000,-0.220000,2.370000,2.370000,0.500000,3.910000,84.000000
83718,2017-04-04,10000,-0.980000,-0.275000,2.440000,2.550000,0.500000,3.595000,54.000000
111624,2017-04-05,10000,-0.970000,-0.330000,2.510000,2.730000,0.500000,3.280000,45.000000
139530,2017-04-06,10000,-1.480000,-0.940000,1.680000,1.680000,1.410000,4.260000,62.000000
167436,2017-04-07,10000,-0.660000,-0.260000,3.460000,3.540000,1.290000,2.990000,43.000000
195342,2017-04-08,10000,-1.290000,-0.730000,0.960000,0.960000,0.860000,3.760000,84.000000
223248,2017-04-09,10000,-0.980000,-0.290000,2.680000,2.680000,0.940000,3.460000,52.000000
251154,2017-04-10,10000,-1.630000,-0.650000,1.360000,1.360000,0.600000,3.850000,85.000000
279060,2017-04-11,10000,-1.100000,-0.440000,3.100000,3.100000,0.990000,3.580000,59.000000
306966,2017-04-12,10000,-0.540000,-0.200000,0.950000,1.630000,0.910000,1.670000,29.000000
334872,2017-04-13,10000,-1.310000,-0.510000,0.840000,0.840000,0.520000,3.820000,83.000000
362778,2017-04-14,10000,-1.290000,-0.330000,1.020000,1.020000,0.770000,3.860000,84.000000
390684,2017-04-15,10000,-1.370000,-0.415000,0.840000,0.840000,0.705000,3.675000,84.000000
418590,2017-04-16,10000,-1.450000,-0.500000,0.660000,0.660000,0.640000,3.490000,84.000000
446496,2017-04-17,10000,-0.940000,-0.110000,3.330000,3.330000,0.760000,3.050000,52.000000
474402,2017-04-18,10000,-1.180000,-0.260000,1.250000,1.250000,0.850000,3.630000,84.000000
502308,2017-04-19,10000,-1.145000,-0.330000,2.290000,2.290000,0.995000,3.510000,84.000000
530214,2017-04-20,10000,-1.110000,-0.400000,3.330000,3.330000,1.140000,3.390000,54.500000
558120,2017-04-21,10000,-1.180000,-0.670000,3.340000,3.300000,1.040000,2.930000,49.000000
586026,2017-04-22,10000,-1.380000,-0.450000,1.330000,1.330000,0.590000,3.780000,84.000000
613932,2017-04-23,10000,-1.310000,-0.340000,1.140000,1.140000,1.180000,4.320000,84.000000
641838,2017-04-24,10000,-1.240000,-0.320000,1.220000,1.220000,0.550000,3.990000,80.000000
669744,2017-04-25,10000,-0.760000,-0.100000,3.160000,3.160000,0.770000,2.970000,52.000000
697650,2017-04-26,10000,-1.110000,-0.480000,2.560000,2.590000,0.770000,1.210000,49.000000
725556,2017-04-27,10000,-1.620000,-0.730000,1.440000,1.440000,0.830000,4.170000,83.000000
753462,2017-04-28,10000,-1.430000,-0.460000,1.140000,1.140000,0.900000,4.110000,84.700000
781368,2017-04-29,10000,-1.180000,-0.550000,1.780000,1.780000,1.030000,4.130000,80.500000
809274,2017-04-30,10000,-1.340000,-0.420000,1.800000,1.800000,0.650000,4.070000,84.000000
...,...,...,...,...,...,...,...,...,...
9348510,2018-03-02,10000,0.335000,1.690000,2.660000,1.525000,-0.465000,4.325000,62.500000
9376416,2018-03-03,10000,-0.370000,1.100000,2.410000,0.810000,-0.820000,4.770000,51.000000
9404322,2018-03-04,10000,0.950000,1.260000,1.400000,0.640000,-4.450000,5.950000,80.000000
9432228,2018-03-05,10000,0.180000,1.420000,1.800000,0.960000,-0.190000,3.770000,61.000000
9460134,2018-03-06,10000,-7.990000,-3.840000,1.650000,3.550000,-4.330000,-0.350000,54.000000
9488040,2018-03-07,10000,1.600000,3.140000,2.370000,1.690000,-0.260000,4.110000,85.000000
9515946,2018-03-08,10000,1.070000,2.170000,2.260000,1.000000,0.310000,4.310000,75.000000
9543852,2018-03-09,10000,-7.630000,-3.850000,2.350000,4.200000,-4.210000,-0.390000,46.000000
9571758,2018-03-10,10000,-7.290000,-3.420000,2.105000,4.140000,-4.435000,0.200000,49.000000
9599664,2018-03-11,10000,-6.950000,-2.990000,1.860000,4.080000,-4.660000,0.790000,52.000000
9627570,2018-03-12,10000,-7.560000,-3.270000,0.600000,2.720000,-4.770000,0.560000,55.000000
9655476,2018-03-13,10000,0.190000,1.300000,2.780000,1.330000,-0.250000,4.180000,50.000000
9683382,2018-03-14,10000,0.400000,1.350000,1.040000,-0.060000,0.160000,4.300000,84.000000
9711288,2018-03-15,10000,-6.960000,-2.710000,1.740000,4.230000,-4.800000,0.730000,56.000000
9739194,2018-03-16,10000,0.000000,0.980000,2.980000,1.700000,-0.020000,4.370000,56.000000
9767100,2018-03-17,10000,-7.730000,-3.610000,0.620000,2.720000,-4.480000,0.980000,51.000000
9795006,2018-03-18,10000,1.080000,2.350000,2.810000,2.090000,-0.440000,4.300000,84.000000
9822912,2018-03-19,10000,0.570000,1.800000,2.550000,1.650000,-0.320000,4.210000,56.000000
9850818,2018-03-20,10000,0.472727,1.703636,2.638182,1.707273,-0.307273,4.223636,55.727273
9878724,2018-03-21,10000,0.375455,1.607273,2.726364,1.764545,-0.294545,4.237273,55.454545
9906630,2018-03-22,10000,0.278182,1.510909,2.814545,1.821818,-0.281818,4.250909,55.181818
9934536,2018-03-23,10000,0.180909,1.414545,2.902727,1.879091,-0.269091,4.264545,54.909091
9962442,2018-03-24,10000,0.083636,1.318182,2.990909,1.936364,-0.256364,4.278182,54.636364
9990348,2018-03-25,10000,-0.013636,1.221818,3.079091,1.993636,-0.243636,4.291818,54.363636
10018254,2018-03-26,10000,-0.110909,1.125455,3.167273,2.050909,-0.230909,4.305455,54.090909
10046160,2018-03-27,10000,-0.208182,1.029091,3.255455,2.108182,-0.218182,4.319091,53.818182
10074066,2018-03-28,10000,-0.305455,0.932727,3.343636,2.165455,-0.205455,4.332727,53.545455
10101972,2018-03-29,10000,-0.402727,0.836364,3.431818,2.222727,-0.192727,4.346364,53.272727
10129878,2018-03-30,10000,-0.500000,0.740000,3.520000,2.280000,-0.180000,4.360000,53.000000
10157784,2018-03-31,10000,-6.980000,-2.790000,1.410000,3.870000,-4.720000,0.800000,51.000000

In [9]:
kilo10001_interpolate =  kilo10001.interpolate(method='index')
kilo10002_interpolate =  kilo10002.interpolate(method='index')
kilo10003_interpolate =  kilo10003.interpolate(method='index')
kilo10004_interpolate =  kilo10004.interpolate(method='index')

kilo10013_interpolate =  kilo10013.interpolate(method='index')
kilo10014_interpolate =  kilo10014.interpolate(method='index')
kilo10015_interpolate =  kilo10015.interpolate(method='index')
kilo10016_interpolate =  kilo10016.interpolate(method='index')
kilo10017_interpolate =  kilo10017.interpolate(method='index')

In [10]:
kilo10000_interpolate.to_csv("../data/kilo10000_interpolate.csv",index=False)
kilo10001_interpolate.to_csv("../data/kilo10001_interpolate.csv",index=False)
kilo10002_interpolate.to_csv("../data/kilo10002_interpolate.csv",index=False)
kilo10003_interpolate.to_csv("../data/kilo10003_interpolate.csv",index=False)
kilo10004_interpolate.to_csv("../data/kilo10004_interpolate.csv",index=False)

kilo10013_interpolate.to_csv("../data/kilo10013_interpolate.csv",index=False)
kilo10014_interpolate.to_csv("../data/kilo10014_interpolate.csv",index=False)
kilo10015_interpolate.to_csv("../data/kilo10015_interpolate.csv",index=False)
kilo10016_interpolate.to_csv("../data/kilo10016_interpolate.csv",index=False)
kilo10017_interpolate.to_csv("../data/kilo10017_interpolate.csv",index=False)

# 機械学習用特徴量

In [83]:
width = 1
lag = 5
target = 10001

read_kilo = list(range(target-width,target+width+1))
data = pd.DataFrame()
for kilo in read_kilo:
    data[str(kilo)] = pd.read_csv("../data/kilo"+str(kilo)+"_interpolate.csv")["高低左"]
data.index = pd.to_datetime(pd.read_csv("../data/kilo"+str(kilo)+"_interpolate.csv")["date"])
data

               10000     10001     10002
date
2017-04-01 -1.160000 -1.170000 -1.090000
2017-04-02 -0.810000 -0.830000 -0.710000
2017-04-03 -0.990000 -0.910000 -0.670000
2017-04-04 -0.980000 -0.810000 -0.500000
2017-04-05 -0.970000 -0.710000 -0.330000
2017-04-06 -1.480000 -1.070000 -0.290000
2017-04-07 -0.660000 -0.560000 -0.460000
2017-04-08 -1.290000 -0.980000 -0.560000
2017-04-09 -0.980000 -0.820000 -0.620000
2017-04-10 -1.630000 -1.450000 -1.060000
2017-04-11 -1.100000 -1.110000 -0.950000
2017-04-12 -0.540000 -0.600000 -0.710000
2017-04-13 -1.310000 -1.140000 -0.820000
2017-04-14 -1.290000 -1.110000 -0.820000
2017-04-15 -1.370000 -1.235000 -1.040000
2017-04-16 -1.450000 -1.360000 -1.260000
2017-04-17 -0.940000 -1.010000 -1.070000
2017-04-18 -1.180000 -1.130000 -1.000000
2017-04-19 -1.145000 -1.045000 -0.925000
2017-04-20 -1.110000 -0.960000 -0.850000
2017-04-21 -1.180000 -1.110000 -0.980000
2017-04-22 -1.380000 -1.310000 -1.140000
2017-04-23 -1.310000 -1.170000 -0.800000
2017-04-24 -1.240000 -1.070000 -0.780000
2017-04-25 -0.760000 -0.750000 -0.820000
2017-04-26 -1.110000 -0.790000 -0.320000
2017-04-27 -1.620000 -1.570000 -1.320000
2017-04-28 -1.430000 -1.450000 -1.370000
2017-04-29 -1.180000 -1.100000 -0.880000
2017-04-30 -1.340000 -1.200000 -0.950000
...              ...       ...       ...
2018-03-02  0.335000  2.875000  5.295000
2018-03-03 -0.370000  2.050000  4.490000
2018-03-04  0.950000  3.270000  5.560000
2018-03-05  0.180000  2.680000  5.100000
2018-03-06 -7.990000 -4.330000  0.070000
2018-03-07  1.600000  4.350000  6.700000
2018-03-08  1.070000  3.780000  6.160000
2018-03-09 -7.630000 -3.820000  0.660000
2018-03-10 -7.290000 -3.325000  1.090000
2018-03-11 -6.950000 -2.830000  1.520000
2018-03-12 -7.560000 -4.000000  0.430000
2018-03-13  0.190000  2.610000  4.910000
2018-03-14  0.400000  2.980000  5.480000
2018-03-15 -6.960000 -3.070000  1.200000
2018-03-16  0.000000  2.490000  4.900000
2018-03-17 -7.730000 -4.190000  0.200000
2018-03-18  1.080000  3.810000  6.250000
2018-03-19  0.570000  3.080000  5.460000
2018-03-20  0.472727  2.967273  5.356364
2018-03-21  0.375455  2.854545  5.252727
2018-03-22  0.278182  2.741818  5.149091
2018-03-23  0.180909  2.629091  5.045455
2018-03-24  0.083636  2.516364  4.941818
2018-03-25 -0.013636  2.403636  4.838182
2018-03-26 -0.110909  2.290909  4.734545
2018-03-27 -0.208182  2.178182  4.630909
2018-03-28 -0.305455  2.065455  4.527273
2018-03-29 -0.402727  1.952727  4.423636
2018-03-30 -0.500000  1.840000  4.320000
2018-03-31 -6.980000 -3.120000  1.210000

[365 rows x 3 columns]

In [86]:
feature = pd.DataFrame()
for lag in list(range(1,lag+1)):
    for kilo in read_kilo:
        feature.loc[:,str(kilo) + "lag"+str(lag)] = data[str(kilo)].shift(-lag)
feature.loc[:,"y"] = data[str(target)].shift(-lag)
feature.index = feature.index + offsets.Day(5)
feature

,10000lag1,10001lag1,10002lag1,10000lag2,10001lag2,10002lag2,10000lag3,10001lag3,10002lag3,10000lag4,10001lag4,10002lag4,10000lag5,10001lag5,10002lag5,y
date,,,,,,,,,,,,,,,,
2017-04-06,-0.810000,-0.830000,-0.710000,-0.990000,-0.910000,-0.670000,-0.980000,-0.810000,-0.500000,-0.970000,-0.710000,-0.330000,-1.480000,-1.070000,-0.290000,-1.070000
2017-04-07,-0.990000,-0.910000,-0.670000,-0.980000,-0.810000,-0.500000,-0.970000,-0.710000,-0.330000,-1.480000,-1.070000,-0.290000,-0.660000,-0.560000,-0.460000,-0.560000
2017-04-08,-0.980000,-0.810000,-0.500000,-0.970000,-0.710000,-0.330000,-1.480000,-1.070000,-0.290000,-0.660000,-0.560000,-0.460000,-1.290000,-0.980000,-0.560000,-0.980000
2017-04-09,-0.970000,-0.710000,-0.330000,-1.480000,-1.070000,-0.290000,-0.660000,-0.560000,-0.460000,-1.290000,-0.980000,-0.560000,-0.980000,-0.820000,-0.620000,-0.820000
2017-04-10,-1.480000,-1.070000,-0.290000,-0.660000,-0.560000,-0.460000,-1.290000,-0.980000,-0.560000,-0.980000,-0.820000,-0.620000,-1.630000,-1.450000,-1.060000,-1.450000
2017-04-11,-0.660000,-0.560000,-0.460000,-1.290000,-0.980000,-0.560000,-0.980000,-0.820000,-0.620000,-1.630000,-1.450000,-1.060000,-1.100000,-1.110000,-0.950000,-1.110000
2017-04-12,-1.290000,-0.980000,-0.560000,-0.980000,-0.820000,-0.620000,-1.630000,-1.450000,-1.060000,-1.100000,-1.110000,-0.950000,-0.540000,-0.600000,-0.710000,-0.600000
2017-04-13,-0.980000,-0.820000,-0.620000,-1.630000,-1.450000,-1.060000,-1.100000,-1.110000,-0.950000,-0.540000,-0.600000,-0.710000,-1.310000,-1.140000,-0.820000,-1.140000
2017-04-14,-1.630000,-1.450000,-1.060000,-1.100000,-1.110000,-0.950000,-0.540000,-0.600000,-0.710000,-1.310000,-1.140000,-0.820000,-1.290000,-1.110000,-0.820000,-1.110000
2017-04-15,-1.100000,-1.110000,-0.950000,-0.540000,-0.600000,-0.710000,-1.310000,-1.140000,-0.820000,-1.290000,-1.110000,-0.820000,-1.370000,-1.235000,-1.040000,-1.235000
2017-04-16,-0.540000,-0.600000,-0.710000,-1.310000,-1.140000,-0.820000,-1.290000,-1.110000,-0.820000,-1.370000,-1.235000,-1.040000,-1.450000,-1.360000,-1.260000,-1.360000
2017-04-17,-1.310000,-1.140000,-0.820000,-1.290000,-1.110000,-0.820000,-1.370000,-1.235000,-1.040000,-1.450000,-1.360000,-1.260000,-0.940000,-1.010000,-1.070000,-1.010000
2017-04-18,-1.290000,-1.110000,-0.820000,-1.370000,-1.235000,-1.040000,-1.450000,-1.360000,-1.260000,-0.940000,-1.010000,-1.070000,-1.180000,-1.130000,-1.000000,-1.130000
2017-04-19,-1.370000,-1.235000,-1.040000,-1.450000,-1.360000,-1.260000,-0.940000,-1.010000,-1.070000,-1.180000,-1.130000,-1.000000,-1.145000,-1.045000,-0.925000,-1.045000
2017-04-20,-1.450000,-1.360000,-1.260000,-0.940000,-1.010000,-1.070000,-1.180000,-1.130000,-1.000000,-1.145000,-1.045000,-0.925000,-1.110000,-0.960000,-0.850000,-0.960000
2017-04-21,-0.940000,-1.010000,-1.070000,-1.180000,-1.130000,-1.000000,-1.145000,-1.045000,-0.925000,-1.110000,-0.960000,-0.850000,-1.180000,-1.110000,-0.980000,-1.110000
2017-04-22,-1.180000,-1.130000,-1.000000,-1.145000,-1.045000,-0.925000,-1.110000,-0.960000,-0.850000,-1.180000,-1.110000,-0.980000,-1.380000,-1.310000,-1.140000,-1.310000
2017-04-23,-1.145000,-1.045000,-0.925000,-1.110000,-0.960000,-0.850000,-1.180000,-1.110000,-0.980000,-1.380000,-1.310000,-1.140000,-1.310000,-1.170000,-0.800000,-1.170000
2017-04-24,-1.110000,-0.960000,-0.850000,-1.180000,-1.110000,-0.980000,-1.380000,-1.310000,-1.140000,-1.310000,-1.170000,-0.800000,-1.240000,-1.070000,-0.780000,-1.070000
2017-04-25,-1.180000,-1.110000,-0.980000,-1.380000,-1.310000,-1.140000,-1.310000,-1.170000,-0.800000,-1.240000,-1.070000,-0.780000,-0.760000,-0.750000,-0.820000,-0.750000
2017-04-26,-1.380000,-1.310000,-1.140000,-1.310000,-1.170000,-0.800000,-1.240000,-1.070000,-0.780000,-0.760000,-0.750000,-0.820000,-1.110000,-0.790000,-0.320000,-0.790000
2017-04-27,-1.310000,-1.170000,-0.800000,-1.240000,-1.070000,-0.780000,-0.760000,-0.750000,-0.820000,-1.110000,-0.790000,-0.320000,-1.620000,-1.570000,-1.320000,-1.570000
2017-04-28,-1.240000,-1.070000,-0.780000,-0.760000,-0.750000,-0.820000,-1.110000,-0.790000,-0.320000,-1.620000,-1.570000,-1.320000,-1.430000,-1.450000,-1.370000,-1.450000
2017-04-29,-0.760000,-0.750000,-0.820000,-1.110000,-0.790000,-0.320000,-1.620000,-1.570000,-1.320000,-1.430000,-1.450000,-1.370000,-1.180000,-1.100000,-0.880000,-1.100000
2017-04-30,-1.110000,-0.790000,-0.320000,-1.620000,-1.570000,-1.320000,-1.430000,-1.450000,-1.370000,-1.180000,-1.100000,-0.880000,-1.340000,-1.200000,-0.950000,-1.200000
2017-05-01,-1.620000,-1.570000,-1.320000,-1.430000,-1.450000,-1.370000,-1.180000,-1.100000,-0.880000,-1.340000,-1.200000,-0.950000,-1.520000,-1.160000,-0.420000,-1.160000
2017-05-02,-1.430000,-1.450000,-1.370000,-1.180000,-1.100000,-0.880000,-1.340000,-1.200000,-0.950000,-1.520000,-1.160000,-0.420000,-1.800000,-1.460000,-0.980000,-1.460000
2017-05-03,-1.180000,-1.100000,-0.880000,-1.340000,-1.200000,-0.950000,-1.520000,-1.160000,-0.420000,-1.800000,-1.460000,-0.980000,-1.540000,-1.470000,-1.250000,-1.470000
2017-05-04,-1.340000,-1.200000,-0.950000,-1.520000,-1.160000,-0.420000,-1.800000,-1.460000,-0.980000,-1.540000,-1.470000,-1.250000,-1.495000,-1.365000,-1.050000,-1.365000
2017-05-05,-1.520000,-1.160000,-0.420000,-1.800000,-1.460000,-0.980000,-1.540000,-1.470000,-1.250000,-1.495000,-1.365000,-1.050000,-1.450000,-1.260000,-0.850000,-1.260000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-03-07,-0.370000,2.050000,4.490000,0.950000,3.270000,5.560000,0.180000,2.680000,5.100000,-7.990000,-4.330000,0.070000,1.600000,4.350000,6.700000,4.350000
2018-03-08,0.950000,3.270000,5.560000,0.180000,2.680000,5.100000,-7.990000,-4.330000,0.070000,1.600000,4.350000,6.700000,1.070000,3.780000,6.160000,3.780000
2018-03-09,0.180000,2.680000,5.100000,-7.990000,-4.330000,0.070000,1.600000,4.350000,6.700000,1.070000,3.780000,6.160000,-7.630000,-3.820000,0.660000,-3.820000
2018-03-10,-7.990000,-4.330000,0.070000,1.600000,4.350000,6.700000,1.070000,3.780000,6.160000,-7.630000,-3.820000,0.660000,-7.290000,-3.325000,1.090000,-3.325000
2018-03-11,1.600000,4.350000,6.700000,1.070000,3.780000,6.160000,-7.630000,-3.820000,0.660000,-7.290000,-3.325000,1.090000,-6.950000,-2.830000,1.520000,-2.830000
2018-03-12,1.070000,3.780000,6.160000,-7.630000,-3.820000,0.660000,-7.290000,-3.325000,1.090000,-6.950000,-2.830000,1.520000,-7.560000,-4.000000,0.430000,-4.000000
2018-03-13,-7.630000,-3.820000,0.660000,-7.290000,-3.325000,1.090000,-6.950000,-2.830000,1.520000,-7.560000,-4.000000,0.430000,0.190000,2.610000,4.910000,2.610000
2018-03-14,-7.290000,-3.325000,1.090000,-6.950000,-2.830000,1.520000,-7.560000,-4.000000,0.430000,0.190000,2.610000,4.910000,0.400000,2.980000,5.480000,2.980000
2018-03-15,-6.950000,-2.830000,1.520000,-7.560000,-4.000000,0.430000,0.190000,2.610000,4.910000,0.400000,2.980000,5.480000,-6.960000,-3.070000,1.200000,-3.070000
2018-03-16,-7.560000,-4.000000,0.430000,0.190000,2.610000,4.910000,0.400000,2.980000,5.480000,-6.960000,-3.070000,1.200000,0.000000,2.490000,4.900000,2.490000
2018-03-17,0.190000,2.610000,4.910000,0.400000,2.980000,5.480000,-6.960000,-3.070000,1.200000,0.000000,2.490000,4.900000,-7.730000,-4.190000,0.200000,-4.190000
2018-03-18,0.400000,2.980000,5.480000,-6.960000,-3.070000,1.200000,0.000000,2.490000,4.900000,-7.730000,-4.190000,0.200000,1.080000,3.810000,6.250000,3.810000
2018-03-19,-6.960000,-3.070000,1.200000,0.000000,2.490000,4.900000,-7.730000,-4.190000,0.200000,1.080000,3.810000,6.250000,0.570000,3.080000,5.460000,3.080000
2018-03-20,0.000000,2.490000,4.900000,-7.730000,-4.190000,0.200000,1.080000,3.810000,6.250000,0.570000,3.080000,5.460000,0.472727,2.967273,5.356364,2.967273
2018-03-21,-7.730000,-4.190000,0.200000,1.080000,3.810000,6.250000,0.570000,3.080000,5.460000,0.472727,2.967273,5.356364,0.375455,2.854545,5.252727,2.854545
2018-03-22,1.080000,3.810000,6.250000,0.570000,3.080000,5.460000,0.472727,2.967273,5.356364,0.375455,2.854545,5.252727,0.278182,2.741818,5.149091,2.741818
2018-03-23,0.570000,3.080000,5.460000,0.472727,2.967273,5.356364,0.375455,2.854545,5.252727,0.278182,2.741818,5.149091,0.180909,2.629091,5.045455,2.629091
2018-03-24,0.472727,2.967273,5.356364,0.375455,2.854545,5.252727,0.278182,2.741818,5.149091,0.180909,2.629091,5.045455,0.083636,2.516364,4.941818,2.516364
2018-03-25,0.375455,2.854545,5.252727,0.278182,2.741818,5.149091,0.180909,2.629091,5.045455,0.083636,2.516364,4.941818,-0.013636,2.403636,4.838182,2.403636
2018-03-26,0.278182,2.741818,5.149091,0.180909,2.629091,5.045455,0.083636,2.516364,4.941818,-0.013636,2.403636,4.838182,-0.110909,2.290909,4.734545,2.290909
2018-03-27,0.180909,2.629091,5.045455,0.083636,2.516364,4.941818,-0.013636,2.403636,4.838182,-0.110909,2.290909,4.734545,-0.208182,2.178182,4.630909,2.178182
2018-03-28,0.083636,2.516364,4.941818,-0.013636,2.403636,4.838182,-0.110909,2.290909,4.734545,-0.208182,2.178182,4.630909,-0.305455,2.065455,4.527273,2.065455
2018-03-29,-0.013636,2.403636,4.838182,-0.110909,2.290909,4.734545,-0.208182,2.178182,4.630909,-0.305455,2.065455,4.527273,-0.402727,1.952727,4.423636,1.952727
2018-03-30,-0.110909,2.290909,4.734545,-0.208182,2.178182,4.630909,-0.305455,2.065455,4.527273,-0.402727,1.952727,4.423636,-0.500000,1.840000,4.320000,1.840000
2018-03-31,-0.208182,2.178182,4.630909,-0.305455,2.065455,4.527273,-0.402727,1.952727,4.423636,-0.500000,1.840000,4.320000,-6.980000,-3.120000,1.210000,-3.120000
2018-04-01,-0.305455,2.065455,4.527273,-0.402727,1.952727,4.423636,-0.500000,1.840000,4.320000,-6.980000,-3.120000,1.210000,NaN,NaN,NaN,NaN
2018-04-02,-0.402727,1.952727,4.423636,-0.500000,1.840000,4.320000,-6.980000,-3.120000,1.210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-04-03,-0.500000,1.840000,4.320000,-6.980000,-3.120000,1.210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-04-04,-6.980000,-3.120000,1.210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-04-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [88]:
feature.to_csv("../data/"+str(target)+"_feature.csv")